In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../cuffdiff/gene_exp.diff", delimiter='\t')
df

,test_id,gene_id,gene,locus,sample_1,sample_2,status,value_1,value_2,log2(fold_change),test_stat,p_value,q_value,significant
0,XLOC_000001,XLOC_000001,evm.TU.AJAPscaffold1.1,AJAPscaffold1:5166-13786,BI,BM,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no
1,XLOC_000002,XLOC_000002,evm.TU.AJAPscaffold1.2,AJAPscaffold1:47719-63453,BI,BM,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no
2,XLOC_000003,XLOC_000003,evm.TU.AJAPscaffold1.3,AJAPscaffold1:77020-114373,BI,BM,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no
3,XLOC_000004,XLOC_000004,evm.TU.AJAPscaffold1.4,AJAPscaffold1:77020-114373,BI,BM,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no
4,XLOC_000005,XLOC_000005,evm.TU.AJAPscaffold1.5,AJAPscaffold1:172599-172920,BI,BM,NOTEST,0.000000,0.000000,0.000000,0.000000,1.00000,1.000000,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3748075,XLOC_035692,XLOC_035692,evm.TU.AJAPscaffold999.13,AJAPscaffold999:238586-260512,RT,RW,NOTEST,0.000000,0.202227,inf,0.000000,1.00000,1.000000,no
3748076,XLOC_035693,XLOC_035693,evm.TU.AJAPscaffold999.4,AJAPscaffold999:78716-86301,RT,RW,OK,10.336300,9.095110,-0.184551,-0.071693,0.69905,0.752211,no
3748077,XLOC_035694,XLOC_035694,evm.TU.AJAPscaffold999.8,AJAPscaffold999:123493-123956,RT,RW,NOTEST,0.000000,0.638801,inf,0.000000,1.00000,1.000000,no
3748078,XLOC_035695,XLOC_035695,evm.TU.AJAPscaffold999.14,AJAPscaffold999:267703-276029,RT,RW,NOTEST,0.745572,0.569140,-0.389565,0.000000,1.00000,1.000000,no
3748079,XLOC_035696,XLOC_035696,evm.TU.AJAPscaffold999.15,AJAPscaffold999:279713-305692,RT,RW,NOTEST,1.776790,1.434200,-0.309024,0.000000,1.00000,1.000000,no

In [3]:
test_df = df[['gene','sample_1','sample_2','value_1','value_2','significant']]
test_df
test_df.to_csv("gene_exp_spliced_diff2.csv")

In [3]:
gene_exp_spliced_diff = pd.read_csv("./gene_exp_spliced_diff.csv")

In [8]:
gene_exp_spliced_diff = gene_exp_spliced_diff.drop(['Unnamed: 0'],axis=1)
gene_exp_spliced_diff

             gene_id sample_1 sample_2    value_1   value_2 significant
0        XLOC_000001       BI       BM   0.000000  0.000000          no
1        XLOC_000002       BI       BM   0.000000  0.000000          no
2        XLOC_000003       BI       BM   0.000000  0.000000          no
3        XLOC_000004       BI       BM   0.000000  0.000000          no
4        XLOC_000005       BI       BM   0.000000  0.000000          no
...              ...      ...      ...        ...       ...         ...
3748075  XLOC_035692       RT       RW   0.000000  0.202227          no
3748076  XLOC_035693       RT       RW  10.336300  9.095110          no
3748077  XLOC_035694       RT       RW   0.000000  0.638801          no
3748078  XLOC_035695       RT       RW   0.745572  0.569140          no
3748079  XLOC_035696       RT       RW   1.776790  1.434200          no

[3748080 rows x 6 columns]